import SongTable from '../components/SongTable'

interface Song {
  title: string;
  datePerformed: string;
  location: string;
  featured: string;
  videoLink: string;
}

const songs: Song[] = [
    { title: 'Dear Reader', datePerformed: '2024-02-07', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
    { title: 'Holy Ground', datePerformed: '2024-02-07', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
    { title: 'Eyes Open', datePerformed: '2024-02-08', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
    { title: 'Electric Touch', datePerformed: '2024-02-08', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
    { title: 'Superman', datePerformed: '2024-02-09', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
    { title: 'The Outside', datePerformed: '2024-02-09', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
    { title: 'Come In With The Rain', datePerformed: '2024-02-10', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
    { title: 'You\'re On Your Own, Kid', datePerformed: '2024-02-10', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
    { title: 'Red', datePerformed: '2024-02-16', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
    { title: 'You\'re Losing Me', datePerformed: '2024-02-16', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
    { title: 'Getaway Car/August/The Other Side of the Door', datePerformed: '2024-02-17', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
    { title: 'this is me trying', datePerformed: '2024-02-17', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
    { title: 'Come Back...Be Here/Daylight', datePerformed: '2024-02-18', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
    { title: 'Teardrops On My Guitar', datePerformed: '2024-02-18', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
    { title: 'How You Get The Girl', datePerformed: '2024-02-23', location: 'Sydney, Australia', featured: '-', videoLink: '' },
    { title: 'White Horse/Coney Island', datePerformed: '2024-02-23', location: 'Sydney, Australia', featured: 'Sabrina Carpenter', videoLink: '' },
    { title: 'Should\'ve Said No/You\'re Not Sorry', datePerformed: '2024-02-24', location: 'Sydney, Australia', featured: '-', videoLink: '' },
    { title: 'New Year\'s Day/Peace', datePerformed: '2024-02-24', location: 'Sydney, Australia', featured: '-', videoLink: '' },
    { title: 'Is It Over Now?/I Wish You Would', datePerformed: '2024-02-25', location: 'Sydney, Australia', featured: '-', videoLink: '' },
    { title: 'Haunted/Exile', datePerformed: '2024-02-25', location: 'Sydney, Australia', featured: '-', videoLink: '' },
    { title: 'Would\'ve Could\'ve Should\'ve/Ivy', datePerformed: '2024-02-26', location: 'Sydney, Australia', featured: '-', videoLink: '' },
    { title: 'Forever & Always/Maroon', datePerformed: '2024-02-26', location: 'Sydney, Australia', featured: '-', videoLink: '' },
    { title: 'Mine/Starlight', datePerformed: '2024-03-02', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'I Don\'t Wanna Live Forever/Dress', datePerformed: '2024-03-02', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'Long Story Short/The Story of Us', datePerformed: '2024-03-03', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'Clean/Evermore', datePerformed: '2024-03-03', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'Foolish One/Tell Me Why', datePerformed: '2024-03-04', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'This Love/Call It What You Want', datePerformed: '2024-03-04', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'Death By A Thousand Cuts/Babe', datePerformed: '2024-03-07', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'Fifteen/You\'re On Your Own, Kid', datePerformed: '2024-03-07', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'Sparks Fly/Gold Rush', datePerformed: '2024-03-08', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'False God/"Slut!"', datePerformed: '2024-03-08', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'Tim McGraw/Cowboy Like Me', datePerformed: '2024-03-09', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'Mirrorball/Epiphany', datePerformed: '2024-03-09', location: 'Singapore, SG', featured: '-', videoLink: '' },
    { title: 'Paris', datePerformed: '2024-05-09', location: 'Paris, France', featured: '-', videoLink: '' },
    { title: 'loml', datePerformed: '2024-05-09', location: 'Paris, France', featured: '-', videoLink: '' },
    { title: 'Is It Over Now?/Out Of The Woods', datePerformed: '2024-05-10', location: 'Paris, France', featured: '-', videoLink: '' },
    { title: 'My Boy Only Breaks His Favourite Toys', datePerformed: '2024-05-10', location: 'Paris, France', featured: '-', videoLink: '' },
    { title: 'Hey Stephen', datePerformed: '2024-05-11', location: 'Paris, France', featured: '-', videoLink: '' },
    { title: 'Maroon', datePerformed: '2024-05-11', location: 'Paris, France', featured: '-', videoLink: '' },
    { title: 'The Alchemy/Treacherous', datePerformed: '2024-05-12', location: 'Paris, France', featured: '-', videoLink: '' },
    { title: 'Begin Again/Paris', datePerformed: '2024-05-12', location: 'Paris, France', featured: '-', videoLink: '' },
    { title: 'I Think He Knows/Gorgeous', datePerformed: '2024-05-17', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
    { title: 'Peter', datePerformed: '2024-05-17', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
    { title: 'Guilty As Sin?', datePerformed: '2024-05-18', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
    { title: 'Say Don\'t Go/Welcome To New York/Clean', datePerformed: '2024-05-18', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
    { title: 'Message In A Bottle/How You Get The Girl/New Romantics', datePerformed: '2024-05-19', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
    { title: 'How Did It End?', datePerformed: '2024-05-19', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
    { title: 'Come Back...Be Here/The Way I Loved You/The Other Side of the Door', datePerformed: '2024-05-24', location: 'Lisbon, Portugal', featured: '-', videoLink: '' },
    { title: 'Fresh Out The Slammer/High Infidelity', datePerformed: '2024-05-24', location: 'Lisbon, Portugal', featured: '-', videoLink: '' },
    { title: 'The Tortured Poets Department/Now That We Don\'t Talk', datePerformed: '2024-05-25', location: 'Lisbon, Portugal', featured: '-', videoLink: '' },
    { title: 'You\'re On Your Own, Kid/Long Live', datePerformed: '2024-05-25', location: 'Lisbon, Portugal', featured: '-', videoLink: '' },
    { title: 'Sparks Fly/I Can Fix Him (No Really I Can)', datePerformed: '2024-05-29', location: 'Madrid, Spain', featured: '-', videoLink: '' },
    { title: 'I Look In People\'s Windows/Snow on the Beach', datePerformed: '2024-05-29', location: 'Madrid, Spain', featured: '-', videoLink: '' },
    { title: 'Our Song/Jump Then Fall', datePerformed: '2024-05-30', location: 'Madrid, Spain', featured: '-', videoLink: '' },
    { title: 'King of my Heart', datePerformed: '2024-05-30', location: 'Madrid, Spain', featured: '-', videoLink: '' },
    { title: 'The Prophecy/Long Story Short', datePerformed: '2024-06-02', location: 'Lyon, France', featured: '-', videoLink: '' },
    { title: 'Fifteen/You\'re On Your Own, Kid', datePerformed: '2024-06-02', location: 'Lyon, France', featured: '-', videoLink: '' },
    { title: 'Glitch/Everything Has Changed', datePerformed: '2024-06-03', location: 'Lyon, France', featured: '-', videoLink: '' },
    { title: 'Chloe, Sam, Sophia or Marcus', datePerformed: '2024-06-03', location: 'Lyon, France', featured: '-', videoLink: '' },
    { title: 'Would\'ve, Could\'ve, Should\'ve/I Know Places', datePerformed: '2024-06-07', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
    { title: '\'Tis The Damn Season/Daylight', datePerformed: '2024-06-07', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
    { title: 'The Bolter/Getaway Car', datePerformed: '2024-06-08', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
    { title: 'All Of The Girls You Loved Before/Crazier', datePerformed: '2024-06-08', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
    { title: 'It\'s Nice To Have A Friend/Dorothea', datePerformed: '2024-06-09', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
    { title: 'Haunted/Exile', datePerformed: '2024-06-09', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
    { title: 'I Can See You/Mine', datePerformed: '2024-06-13', location: 'Liverpool, UK', featured: '-', videoLink: '' },
    { title: 'Cornelia Street/Maroon', datePerformed: '2024-06-13', location: 'Liverpool, UK', featured: '-', videoLink: '' },
    { title: 'This Is What You Came For/Gold Rush', datePerformed: '2024-06-14', location: 'Liverpool, UK', featured: '-', videoLink: '' },
    { title: 'The Great War/You\'re Losing Me', datePerformed: '2024-06-14', location: 'Liverpool, UK', featured: '-', videoLink: '' },
    { title: 'Carolina/No Body, No Crime', datePerformed: '2024-06-15', location: 'Liverpool, UK', featured: '-', videoLink: '' },
    { title: 'The Manuscript/Red', datePerformed: '2024-06-15', location: 'Liverpool, UK', featured: '-', videoLink: '' },
    { title: 'I Forgot That You Existed/This Is Why We Can\'t Have Nice Things', datePerformed: '2024-06-18', location: 'Cardiff, UK', featured: '-', videoLink: '' },
    { title: 'I Hate It Here/the lakes', datePerformed: '2024-06-18', location: 'Cardiff, UK', featured: '-', videoLink: '' },
    { title: 'Hits Different/Death By A Thousand Cuts', datePerformed: '2024-06-21', location: 'London, UK', featured: '-', videoLink: '' },
    { title: 'The Black Dog/Come Back...Be Here/Maroon', datePerformed: '2024-06-21', location: 'London, UK', featured: '-', videoLink: '' },
    { title: 'thanK you aIMee/Mean', datePerformed: '2024-06-22', location: 'London, UK', featured: '-', videoLink: '' },
    { title: 'Castles Crumbling', datePerformed: '2024-06-22', location: 'London, UK', featured: 'Hayley Williams', videoLink: '' },
    { title: 'us', datePerformed: '2024-06-23', location: 'London, UK', featured: 'Gracie Abrams', videoLink: '' },
    { title: 'Out of the Woods/Is It Over Now?/Clean', datePerformed: '2024-06-23', location: 'London, UK', featured: '-', videoLink: '' },
    { title: 'State of Grace/You\'re On Your Own, Kid', datePerformed: '2024-06-28', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
    { title: 'Sweet Nothing/Hoax', datePerformed: '2024-06-28', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
    { title: 'The Albatross/Dancing With Our Hands Tied', datePerformed: '2024-06-29', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
    { title: 'This Love/Ours', datePerformed: '2024-06-29', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
    { title: 'Clara Bow/The Lucky One', datePerformed: '2024-06-30', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
    { title: 'You\'re On Your Own, Kid', datePerformed: '2024-06-30', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
    { title: 'Guilty As Sin?/Untouchable', datePerformed: '2024-07-04', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
    { title: 'The Archer/Question...?', datePerformed: '2024-07-04', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
    { title: 'imgonnagetyouback/Dress', datePerformed: '2024-07-05', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
    { title: 'You Are In Love/Cowboy Like Me', datePerformed: '2024-07-05', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
    { title: 'Sweeter Than Fiction/Holy Ground', datePerformed: '2024-07-06', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
    { title: 'Mary\'s Song (Oh My My My)/So High School/Everything Has Changed', datePerformed: '2024-07-06', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
    { title: 'Right Where You Left Me/All You Had To Do Was Stay', datePerformed: '2024-07-09', location: 'Zürich, Switzerland', featured: '-', videoLink: '' },
    { title: 'Last Kiss/Sad Beautiful Tragic', datePerformed: '2024-07-09', location: 'Zürich, Switzerland', featured: '-', videoLink: '' },
    { title: 'Closure/A Perfectly Good Heart', datePerformed: '2024-07-10', location: 'Zürich, Switzerland', featured: '-', videoLink: '' },
    { title: 'Robin/Never Grow Up', datePerformed: '2024-07-10', location: 'Zürich, Switzerland', featured: '-', videoLink: '' },
    { title: 'The 1/Wonderland', datePerformed: '2024-07-13', location: 'Milan, Italy', featured: '-', videoLink: '' },
    { title: 'I Almost Do/The Moment I Knew', datePerformed: '2024-07-13', location: 'Milan, Italy', featured: '-', videoLink: '' },
    { title: 'Mr. Perfectly Fine/Red', datePerformed: '2024-07-14', location: 'Milan, Italy', featured: '-', videoLink: '' },
    { title: 'Getaway Car/Out of the Woods', datePerformed: '2024-07-14', location: 'Milan, Italy', featured: '-', videoLink: '' },
    { title: 'Superstar/Invisible String', datePerformed: '2024-07-17', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
    { title: '"Slut!"/False God', datePerformed: '2024-07-17', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
    { title: 'Speak Now/Hey Stephen', datePerformed: '2024-07-18', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
    { title: 'This Is Me Trying/Labyrinth', datePerformed: '2024-07-18', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
    { title: 'Paper Rings/Stay Stay Stay', datePerformed: '2024-07-19', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
    { title: 'it\'s time to go/Better Man', datePerformed: '2024-07-19', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
    { title: 'Teardrops On My Guitar/The Last Time', datePerformed: '2024-07-23', location: 'Hamburg, Germany', featured: '-', videoLink: '' },
    { title: 'We Were Happy/Happiness', datePerformed: '2024-07-23', location: 'Hamburg, Germany', featured: '-', videoLink: '' },
    { title: 'The Last Great American Dynasty/Run', datePerformed: '2024-07-24', location: 'Hamburg, Germany', featured: '-', videoLink: '' },
    { title: 'Nothing New/Dear Reader', datePerformed: '2024-07-24', location: 'Hamburg, Germany', featured: '-', videoLink: '' },  
    { title: 'mirrorball', datePerformed: '2024-03-17', location: 'Glendale, AZ', featured: '-', videoLink: '' },
    { title: 'Tim McGraw', datePerformed: '2024-03-17', location: 'Glendale, AZ', featured: '-', videoLink: '' },
    { title: 'State of Grace', datePerformed: '2024-03-18', location: 'Glendale, AZ', featured: '-', videoLink: '' },
    { title: 'this is me trying', datePerformed: '2024-03-18', location: 'Glendale, AZ', featured: '-', videoLink: '' },
    { title: 'Our Song', datePerformed: '2024-03-24', location: 'Las Vegas, NV', featured: '-', videoLink: '' },
    { title: 'Snow on the Beach', datePerformed: '2024-03-24', location: 'Las Vegas, NV', featured: '-', videoLink: '' },
    { title: 'cowboy like me', datePerformed: '2024-03-25', location: 'Las Vegas, NV', featured: 'Marcus Mumford', videoLink: '' },
    { title: 'White Horse', datePerformed: '2024-03-25', location: 'Las Vegas, NV', featured: '-', videoLink: '' },
    { title: 'Sad Beautiful Tragic', datePerformed: '2024-03-31', location: 'Arlington, TX', featured: '-', videoLink: '' },
    { title: 'Ours', datePerformed: '2024-03-31', location: 'Arlington, TX', featured: '-', videoLink: '' },
    { title: 'Death By a Thousand Cuts', datePerformed: '2024-04-01', location: 'Arlington, TX', featured: '-', videoLink: '' },
    { title: 'Clean', datePerformed: '2024-04-01', location: 'Arlington, TX', featured: '-', videoLink: '' },
    { title: 'Jump Then Fall', datePerformed: '2024-04-02', location: 'Arlington, TX', featured: '-', videoLink: '' },
    { title: 'The Lucky One', datePerformed: '2024-04-02', location: 'Arlington, TX', featured: '-', videoLink: '' },
    { title: 'Speak Now', datePerformed: '2024-04-13', location: 'Tampa, FL', featured: '-', videoLink: '' },
    { title: 'Treacherous', datePerformed: '2024-04-13', location: 'Tampa, FL', featured: '-', videoLink: '' },
    { title: 'The Great War', datePerformed: '2024-04-14', location: 'Tampa, FL', featured: 'Aaron Dessner', videoLink: '' },
    { title: 'You\'re On Your Own, Kid', datePerformed: '2024-04-14', location: 'Tampa, FL', featured: '-', videoLink: '' },
    { title: 'mad woman', datePerformed: '2024-04-15', location: 'Tampa, FL', featured: 'Aaron Dessner', videoLink: '' },
    { title: 'Mean', datePerformed: '2024-04-15', location: 'Tampa, FL', featured: '-', videoLink: '' },
    { title: 'Wonderland', datePerformed: '2024-04-21', location: 'Houston, TX', featured: '-', videoLink: '' },
    { title: 'You\'re Not Sorry', datePerformed: '2024-04-21', location: 'Houston, TX', featured: '-', videoLink: '' },
    { title: 'A Place In This World', datePerformed: '2024-04-22', location: 'Houston, TX', featured: '-', videoLink: '' },
    { title: 'Today Was A Fairytale', datePerformed: '2024-04-22', location: 'Houston, TX', featured: '-', videoLink: '' },
    { title: 'Begin Again', datePerformed: '2024-04-23', location: 'Houston, TX', featured: '-', videoLink: '' },
    { title: 'Cold as You', datePerformed: '2024-04-23', location: 'Houston, TX', featured: '-', videoLink: '' },
    { title: 'The Other Side of the Door', datePerformed: '2024-04-28', location: 'Atlanta, GA', featured: '-', videoLink: '' },
    { title: 'Coney Island', datePerformed: '2024-04-28', location: 'Atlanta, GA', featured: '-', videoLink: '' },
    { title: 'High Infidelity', datePerformed: '2024-04-29', location: 'Atlanta, GA', featured: '-', videoLink: '' },
    { title: 'Gorgeous', datePerformed: '2024-04-29', location: 'Atlanta, GA', featured: '-', videoLink: '' },
    { title: 'I Bet You Think About Me', datePerformed: '2024-04-30', location: 'Atlanta, GA', featured: '-', videoLink: '' },
    { title: 'How You Get The Girl', datePerformed: '2024-04-30', location: 'Atlanta, GA', featured: '-', videoLink: '' },
    { title: 'Sparks Fly', datePerformed: '2024-05-05', location: 'Nashville, TN', featured: '-', videoLink: '' },
    { title: 'Teardrops On My Guitar', datePerformed: '2024-05-05', location: 'Nashville, TN', featured: '-', videoLink: '' },
    { title: 'Out of the Woods', datePerformed: '2024-05-06', location: 'Nashville, TN', featured: '-', videoLink: '' },
    { title: 'Fifteen', datePerformed: '2024-05-06', location: 'Nashville, TN', featured: '-', videoLink: '' },
    { title: 'Would\'ve Could\'ve Should\'ve', datePerformed: '2024-05-07', location: 'Nashville, TN', featured: 'Aaron Dessner', videoLink: '' },
    { title: 'Mine', datePerformed: '2024-05-07', location: 'Nashville, TN', featured: '-', videoLink: '' },
    { title: 'gold rush', datePerformed: '2024-05-12', location: 'Philadelphia, PA', featured: '-', videoLink: '' },
    { title: 'Come Back... Be Here', datePerformed: '2024-05-12', location: 'Philadelphia, PA', featured: '-', videoLink: '' },
    { title: 'Forever & Always', datePerformed: '2024-05-13', location: 'Philadelphia, PA', featured: '-', videoLink: '' },
    { title: 'This Love', datePerformed: '2024-05-13', location: 'Philadelphia, PA', featured: '-', videoLink: '' },
    { title: 'Hey Stephen', datePerformed: '2024-05-14', location: 'Philadelphia, PA', featured: '-', videoLink: '' },
    { title: 'The Best Day', datePerformed: '2024-05-14', location: 'Philadelphia, PA', featured: '-', videoLink: '' },
    { title: 'Should\'ve Said No', datePerformed: '2024-05-19', location: 'Foxborough, MA', featured: '-', videoLink: '' },
    { title: 'Better Man', datePerformed: '2024-05-19', location: 'Foxborough, MA', featured: '-', videoLink: '' },
    { title: 'Question...?', datePerformed: '2024-05-20', location: 'Foxborough, MA', featured: '-', videoLink: '' },
    { title: 'Invisible', datePerformed: '2024-05-20', location: 'Foxborough, MA', featured: '-', videoLink: '' },
    { title: 'I Think He Knows', datePerformed: '2024-05-21', location: 'Foxborough, MA', featured: '-', videoLink: '' },
    { title: 'Red', datePerformed: '2024-05-21', location: 'Foxborough, MA', featured: '-', videoLink: '' },
    { title: 'Getaway Car', datePerformed: '2024-05-26', location: 'East Rutherford, NJ', featured: 'Jack Antonoff', videoLink: '' },
    { title: 'Maroon', datePerformed: '2024-05-26', location: 'East Rutherford, NJ', featured: '-', videoLink: '' },
    { title: 'Holy Ground', datePerformed: '2024-05-27', location: 'East Rutherford, NJ', featured: '-', videoLink: '' },
    { title: 'False God', datePerformed: '2024-05-27', location: 'East Rutherford, NJ', featured: '-', videoLink: '' },
    { title: 'Welcome To New York', datePerformed: '2024-05-28', location: 'East Rutherford, NJ', featured: '-', videoLink: '' },
    { title: 'Clean', datePerformed: '2024-05-28', location: 'East Rutherford, NJ', featured: '-', videoLink: '' },
    { title: 'I Wish You Would', datePerformed: '2024-06-02', location: 'Chicago, IL', featured: '-', videoLink: '' },
    { title: 'the lakes', datePerformed: '2024-06-02', location: 'Chicago, IL', featured: '-', videoLink: '' },
    { title: 'You All Over Me', datePerformed: '2024-06-03', location: 'Chicago, IL', featured: 'Maren Morris', videoLink: '' },
    { title: 'I Don\'t Wanna Live Forever', datePerformed: '2024-06-03', location: 'Chicago, IL', featured: '-', videoLink: '' },
    { title: 'Hits Different', datePerformed: '2024-06-04', location: 'Chicago, IL', featured: '-', videoLink: '' },
    { title: 'The Moment I Knew', datePerformed: '2024-06-04', location: 'Chicago, IL', featured: '-', videoLink: '' },
    { title: 'Haunted', datePerformed: '2024-06-09', location: 'Detroit, MI', featured: '-', videoLink: '' },
    { title: 'I Almost Do', datePerformed: '2024-06-09', location: 'Detroit, MI', featured: '-', videoLink: '' },
    { title: 'All You Had To Do Was Stay', datePerformed: '2024-06-10', location: 'Detroit, MI', featured: '-', videoLink: '' },
    { title: 'Breathe', datePerformed: '2024-06-10', location: 'Detroit, MI', featured: '-', videoLink: '' },
    { title: 'Mr. Perfectly Fine', datePerformed: '2024-06-16', location: 'Pittsburgh, PA', featured: '-', videoLink: '' },
    { title: 'The Last Time', datePerformed: '2024-06-16', location: 'Pittsburgh, PA', featured: '-', videoLink: '' },
    { title: 'seven', datePerformed: '2024-06-17', location: 'Pittsburgh, PA', featured: 'Aaron Dessner', videoLink: '' },
    { title: 'The Story of Us', datePerformed: '2024-06-17', location: 'Pittsburgh, PA', featured: '-', videoLink: '' },
    { title: 'Paper Rings', datePerformed: '2024-06-23', location: 'Minneapolis, MN', featured: '-', videoLink: '' },
    { title: 'If This Was A Movie', datePerformed: '2024-06-23', location: 'Minneapolis, MN', featured: '-', videoLink: '' },
    { title: 'Dear John', datePerformed: '2024-06-24', location: 'Minneapolis, MN', featured: '-', videoLink: '' },
    { title: 'Daylight', datePerformed: '2024-06-24', location: 'Minneapolis, MN', featured: '-', videoLink: '' },
    { title: 'I\'m Only Me When I\'m With You', datePerformed: '2024-06-30', location: 'Cincinnati, OH', featured: '-', videoLink: '' },
    { title: 'evermore', datePerformed: '2024-06-30', location: 'Cincinnati, OH', featured: '-', videoLink: '' },
    { title: 'ivy', datePerformed: '2024-07-01', location: 'Cincinnati, OH', featured: 'Aaron Dessner', videoLink: '' },
    { title: 'I miss you, I’m sorry', datePerformed: '2024-07-01', location: 'Cincinnati, OH', featured: 'Gracie Abrams', videoLink: '' },
    { title: 'Call It What You Want', datePerformed: '2024-07-01', location: 'Cincinnati, OH', featured: '-', videoLink: '' },
    { title: 'Never Grow Up', datePerformed: '2024-07-07', location: 'Kansas City, MO', featured: '-', videoLink: '' },
    { title: 'When Emma Falls in Love', datePerformed: '2024-07-07', location: 'Kansas City, MO', featured: '-', videoLink: '' },
    { title: 'Last Kiss', datePerformed: '2024-07-08', location: 'Kansas City, MO', featured: '-', videoLink: '' },
    { title: 'dorothea', datePerformed: '2024-07-08', location: 'Kansas City, MO', featured: '-', videoLink: '' },
    { title: 'Picture To Burn', datePerformed: '2024-07-14', location: 'Denver, CO', featured: '-', videoLink: '' },
    { title: 'Timeless', datePerformed: '2024-07-14', location: 'Denver, CO', featured: '-', videoLink: '' },
    { title: 'Starlight', datePerformed: '2024-07-15', location: 'Denver, CO', featured: '-', videoLink: '' },
    { title: 'Back To December', datePerformed: '2024-07-15', location: 'Denver, CO', featured: '-', videoLink: '' },
    { title: 'This Is Why We Can\'t Have Nice Things', datePerformed: '2024-07-22', location: 'Seattle, WA', featured: '-', videoLink: '' },
    { title: 'Everything Has Changed', datePerformed: '2024-07-22', location: 'Seattle, WA', featured: '-', videoLink: '' },
    { title: 'Message In A Bottle', datePerformed: '2024-07-23', location: 'Seattle, WA', featured: '-', videoLink: '' },
    { title: 'Tied Together With A Smile', datePerformed: '2024-07-23', location: 'Seattle, WA', featured: '-', videoLink: '' },
    { title: 'right where you left me', datePerformed: '2024-07-28', location: 'Santa Clara, CA', featured: 'Aaron Dessner', videoLink: '' },
    { title: 'Castles Crumbling', datePerformed: '2024-07-28', location: 'Santa Clara, CA', featured: '-', videoLink: '' },
    { title: 'Stay Stay Stay', datePerformed: '2024-07-29', location: 'Santa Clara, CA', featured: '-', videoLink: '' },
    { title: 'All of the Girls You\'ve Loved Before', datePerformed: '2024-07-29', location: 'Santa Clara, CA', featured: '-', videoLink: '' },
    { title: 'I Can See You', datePerformed: '2024-08-03', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'Maroon', datePerformed: '2024-08-03', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'Our Song', datePerformed: '2024-08-04', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'You Are In Love', datePerformed: '2024-08-04', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'Death By A Thousand Cuts', datePerformed: '2024-08-05', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'You\'re On Your Own, Kid', datePerformed: '2024-08-05', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'Dress', datePerformed: '2024-08-07', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'exile', datePerformed: '2024-08-07', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'I Know Places', datePerformed: '2024-08-08', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'King of My Heart', datePerformed: '2024-08-08', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'New Romantics', datePerformed: '2024-08-09', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'New Year\'s Day', datePerformed: '2024-08-09', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
    { title: 'I Forgot That You Existed', datePerformed: '2024-08-24', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
    { title: 'Sweet Nothing', datePerformed: '2024-08-24', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
    { title: 'Tell Me Why', datePerformed: '2024-08-25', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
    { title: 'Snow on the Beach', datePerformed: '2024-08-25', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
    { title: 'Cornelia Street', datePerformed: '2024-08-26', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
    { title: 'You Belong With Me', datePerformed: '2024-08-26', location: 'Mexico City, Mexico', featured: '-', videoLink: '' }  
]


export default function Home() {
  return (
    <div className="container mx-auto px-4">
      <h1 className="text-3xl font-bold text-center my-8">Song List</h1>
      <SongTable songs={songs} />
    </div>
  )
}