const SongsArray = [
    { title: 'mirrorball', datePerformed: '2023-03-17', location: 'Glendale, AZ', featured: '-', videoLink: 'https://www.youtube.com/watch?v=EajJWJpQa_0&pp=ygU7R2xlbmRhbGUsIEFaIChNYXJjaCAxNykgLSDigJhtaXJyb3JiYWxs4oCZIGFuZCAnVGltIE1jR3Jhdyc%3D' },
      { title: 'Tim McGraw', datePerformed: '2023-03-17', location: 'Glendale, AZ', featured: '-', videoLink: 'https://www.youtube.com/watch?v=6nzfuyRYcV0&pp=ygU7R2xlbmRhbGUsIEFaIChNYXJjaCAxNykgLSDigJhtaXJyb3JiYWxs4oCZIGFuZCAnVGltIE1jR3Jhdyc%3D' },
      { title: 'State of Grace', datePerformed: '2023-03-18', location: 'Glendale, AZ', featured: '-', videoLink: 'https://www.youtube.com/watch?v=wEWpH131WFg&pp=ygUvR2xlbmRhbGUsIEFaIChNYXJjaCAxOCkgLSDigJhTdGF0ZSBvZiBHcmFjZeKAmSA%3D' },
      { title: 'this is me trying', datePerformed: '2023-03-18', location: 'Glendale, AZ', featured: '-', videoLink: 'https://www.youtube.com/watch?v=37DpyRnUHck&pp=ygUuR2xlbmRhbGUsIEFaIChNYXJjaCAxOCkgLSDigJh0aGlzIGlzIG1lIHRyeWluZw%3D%3D' },
      { title: 'Our Song', datePerformed: '2023-03-24', location: 'Las Vegas, NV', featured: '-', videoLink: 'https://www.youtube.com/watch?v=7uoV9vbz1xQ&pp=ygU9TGFzIFZlZ2FzLCBOViAoTWFyY2ggMjQpIC0gJ091ciBTb25nJyBhbmQgJ1Nub3cgb24gdGhlIEJlYWNoJw%3D%3D' },
      { title: 'Snow on the Beach', datePerformed: '2023-03-24', location: 'Las Vegas, NV', featured: '-', videoLink: 'https://www.youtube.com/watch?v=69nMfO9uuFg&pp=ygU9TGFzIFZlZ2FzLCBOViAoTWFyY2ggMjQpIC0gJ091ciBTb25nJyBhbmQgJ1Nub3cgb24gdGhlIEJlYWNoJw%3D%3D' },
      { title: 'cowboy like me', datePerformed: '2023-03-25', location: 'Las Vegas, NV', featured: 'Marcus Mumford', videoLink: 'https://www.youtube.com/watch?v=MTvzFTlyg-4&pp=ygVTTGFzIFZlZ2FzLCBOViAoTWFyY2ggMjUpIC0gJ2Nvd2JveSBsaWtlIG1lJyAod2l0aCBNYXJjdXMgTXVtZm9yZCkgYW5kICdXaGl0ZSBIb3JzZSc%3D' },
      { title: 'White Horse', datePerformed: '2023-03-25', location: 'Las Vegas, NV', featured: '-', videoLink: 'https://www.youtube.com/shorts/A91FV0ZdCfE' },
      { title: 'Sad Beautiful Tragic', datePerformed: '2023-03-31', location: 'Arlington, TX', featured: '-', videoLink: 'https://www.youtube.com/watch?v=xG6KOMAVvEM&pp=ygU8QXJsaW5ndG9uLCBUWCAoTWFyY2ggMzEpIC0gJ1NhZCBCZWF1dGlmdWwgVHJhZ2ljJyBhbmQgJ091cnMn' },
      { title: 'Ours', datePerformed: '2023-03-31', location: 'Arlington, TX', featured: '-', videoLink: 'https://www.youtube.com/shorts/2MTsVipbxBE' },
      { title: 'Death By a Thousand Cuts', datePerformed: '2023-04-01', location: 'Arlington, TX', featured: '-', videoLink: 'https://www.youtube.com/watch?v=MMshQUubrZo&pp=ygU1QXJsaW5ndG9uLCBUWCAoQXByaWwgMSkgLSAnRGVhdGggQnkgYSBUaG91c2FuZCBDdXRzJyA%3D' },
      { title: 'Clean', datePerformed: '2023-04-01', location: 'Arlington, TX', featured: '-', videoLink: 'https://www.youtube.com/shorts/78bxm4s_DJw' },
      { title: 'Jump Then Fall', datePerformed: '2023-04-02', location: 'Arlington, TX', featured: '-', videoLink: 'https://www.youtube.com/watch?v=6od2Mpa7o_0&pp=ygU-QXJsaW5ndG9uLCBUWCAoQXByaWwgMikgLSAnSnVtcCBUaGVuIEZhbGwnIGFuZCAnVGhlIEx1Y2t5IE9uZSc%3D' },
      { title: 'The Lucky One', datePerformed: '2023-04-02', location: 'Arlington, TX', featured: '-', videoLink: 'https://www.youtube.com/watch?v=WS-Ajik76pE&pp=ygU-QXJsaW5ndG9uLCBUWCAoQXByaWwgMikgLSAnSnVtcCBUaGVuIEZhbGwnIGFuZCAnVGhlIEx1Y2t5IE9uZSc%3D' },
      { title: 'Speak Now', datePerformed: '2023-04-13', location: 'Tampa, FL', featured: '-', videoLink: 'https://www.youtube.com/watch?v=hlTf6V3b9Eo&pp=ygU0VGFtcGEsIEZMIChBcHJpbCAxMykgLSAnU3BlYWsgTm93JyBhbmQgJ1RyZWFjaGVyb3VzJw%3D%3D' },
      { title: 'Treacherous', datePerformed: '2023-04-13', location: 'Tampa, FL', featured: '-', videoLink: 'https://www.youtube.com/watch?v=9lhc41SEACw&pp=ygUlVGFtcGEsIEZMIChBcHJpbCAxMykgLSAgJ1RyZWFjaGVyb3VzJw%3D%3D' },
      { title: 'The Great War', datePerformed: '2023-04-14', location: 'Tampa, FL', featured: 'Aaron Dessner', videoLink: 'https://www.youtube.com/watch?v=GMEfRM7Py6c&pp=ygUnVGFtcGEsIEZMIChBcHJpbCAxNCkgLSAnVGhlIEdyZWF0IFdhcicg' },
      { title: 'You\'re On Your Own, Kid', datePerformed: '2023-04-14', location: 'Tampa, FL', featured: '-', videoLink: 'https://www.youtube.com/watch?v=FWfzbEG7wDQ&pp=ygUodGFtcGEgZmwgKGFwcmlsIDE0KSAtIHlvdXJlIG9uIHlvdXIgb3duIA%3D%3D' },
      { title: 'mad woman', datePerformed: '2023-04-15', location: 'Tampa, FL', featured: 'Aaron Dessner', videoLink: 'https://www.youtube.com/watch?v=TuZcs7jFgWs&pp=ygU5IFRhbXBhLCBGTCAoQXByaWwgMTUpIC0gJ21hZCB3b21hbicgKHdpdGggQWFyb24gRGVzc25lcikg' },
      { title: 'Mean', datePerformed: '2023-04-15', location: 'Tampa, FL', featured: '-', videoLink: 'https://www.youtube.com/shorts/z42rx5u56HI' },
      { title: 'Wonderland', datePerformed: '2023-04-21', location: 'Houston, TX', featured: '-', videoLink: 'https://www.youtube.com/shorts/IozKfRhWQ2s' },
      { title: 'You\'re Not Sorry', datePerformed: '2023-04-21', location: 'Houston, TX', featured: '-', videoLink: 'https://www.youtube.com/shorts/uTvEPexwRfs' },
      { title: 'A Place In This World', datePerformed: '2023-04-22', location: 'Houston, TX', featured: '-', videoLink: 'https://www.youtube.com/watch?v=c6BBQLkvt9w&pp=ygUxSG91c3RvbiwgVFggKEFwcmlsIDIyKSDigJMgJ0EgUGxhY2UgSW4gVGhpcyBXb3JsZA%3D%3D' },
      { title: 'Today Was A Fairytale', datePerformed: '2023-04-22', location: 'Houston, TX', featured: '-', videoLink: 'https://www.youtube.com/watch?v=ntJPoUM3RZQ&pp=ygUwaG91c3RvbiB0eCAoYXByaWwgMjIpIOKAkyB0b2RheSB3YXMgYSBmYWlyeXRhbGUg' },
      { title: 'Begin Again', datePerformed: '2023-04-23', location: 'Houston, TX', featured: '-', videoLink: 'https://www.youtube.com/shorts/xqW43zIM3Ds' },
      { title: 'Cold as You', datePerformed: '2023-04-23', location: 'Houston, TX', featured: '-', videoLink: 'https://www.youtube.com/watch?v=ZpVwnkcGVig&ab_channel=LaurenBerlin' },
      { title: 'The Other Side of the Door', datePerformed: '2023-04-28', location: 'Atlanta, GA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=xT9xsW98-1Q&ab_channel=JaclynMarie' },
      { title: 'Coney Island', datePerformed: '2023-04-28', location: 'Atlanta, GA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=BBm6I9I1kXM&ab_channel=mei' },
      { title: 'High Infidelity', datePerformed: '2023-04-29', location: 'Atlanta, GA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=5mnGo5WBqVc&ab_channel=JosephCronin' },
      { title: 'Gorgeous', datePerformed: '2023-04-29', location: 'Atlanta, GA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=1dwKGTe_4gE&ab_channel=JayJay' },
      { title: 'I Bet You Think About Me', datePerformed: '2023-04-30', location: 'Atlanta, GA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=9eX7FgXfrEQ&ab_channel=JaclynMarie' },
      { title: 'How You Get The Girl', datePerformed: '2023-04-30', location: 'Atlanta, GA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=YOiIc4_U5zc&ab_channel=kristylittlejohnmyvideos' },
      { title: 'Sparks Fly', datePerformed: '2023-05-05', location: 'Nashville, TN', featured: '-', videoLink: 'https://www.youtube.com/watch?v=_Q5cGR8cDFw&pp=ygUnTmFzaHZpbGxlLCBUTiAoTWF5IDUpIOKAkyAnU3BhcmtzIEZseScg' },
      { title: 'Teardrops On My Guitar', datePerformed: '2023-05-05', location: 'Nashville, TN', featured: '-', videoLink: 'https://www.youtube.com/watch?v=Qyv5uZqdTGw&pp=ygUxTmFzaHZpbGxlLCBUTiAoTWF5IDUpIOKAkyBUZWFyZHJvcHMgT24gTXkgR3VpdGFyJw%3D%3D' },
      { title: 'Out of the Woods', datePerformed: '2023-05-06', location: 'Nashville, TN', featured: '-', videoLink: 'https://www.youtube.com/watch?v=SrBtq4g4mLc&pp=ygU6TmFzaHZpbGxlLCBUTiAoTWF5IDYpIOKAkyAnT3V0IG9mIHRoZSBXb29kcycgYW5kICdGaWZ0ZWVuJw%3D%3D' },
      { title: 'Fifteen', datePerformed: '2023-05-06', location: 'Nashville, TN', featured: '-', videoLink: 'https://www.youtube.com/shorts/A6N7F-GyWmU' },
      { title: 'Would\'ve Could\'ve Should\'ve', datePerformed: '2023-05-07', location: 'Nashville, TN', featured: 'Aaron Dessner', videoLink: 'https://www.youtube.com/watch?v=p8fgaT_i6jg&pp=ygVNTmFzaHZpbGxlLCBUTiAoTWF5IDcpIOKAkyAnV291bGQndmUgQ291bGQndmUgU2hvdWxkJ3ZlJyAod2l0aCBBYXJvbiBEZXNzbmVyKSA%3D' },
      { title: 'Mine', datePerformed: '2023-05-07', location: 'Nashville, TN', featured: '-', videoLink: 'https://www.youtube.com/shorts/T9i1xPD10Bc' },
      { title: 'gold rush', datePerformed: '2023-05-12', location: 'Philadelphia, PA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=6S2m8zdniMs&pp=ygUnUGhpbGFkZWxwaGlhLCBQQSAoTWF5IDEyKSAtICdnb2xkIHJ1c2gn' },
      { title: 'Come Back... Be Here', datePerformed: '2023-05-12', location: 'Philadelphia, PA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=cqC-zVyBkiE&pp=ygUtUGhpbGFkZWxwaGlhLCBQQSAoTWF5IDEyKSAtIGNvbWUgYmFjayBiZSBoZXJl' },
      { title: 'Forever & Always', datePerformed: '2023-05-13', location: 'Philadelphia, PA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=C1ThXFtzdbM&pp=ygUuUGhpbGFkZWxwaGlhLCBQQSAoTWF5IDEzKSAtICdGb3JldmVyICYgQWx3YXlzJw%3D%3D' },
      { title: 'This Love', datePerformed: '2023-05-13', location: 'Philadelphia, PA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=w37iyhktvTk&pp=ygUsUGhpbGFkZWxwaGlhLCBQQSAoTWF5IDEzKSAtIHRoaXMgbG92ZSB0YXlsb3I%3D' },
      { title: 'Hey Stephen', datePerformed: '2023-05-14', location: 'Philadelphia, PA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=f7r2ZWSRmW8&pp=ygUkUGhpbGFkZWxwaGlhLCBQQSAoTWF5IDE0IGhleSBzdGVwaGVu' },
      { title: 'The Best Day', datePerformed: '2023-05-14', location: 'Philadelphia, PA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=fth-WOX0f70&pp=ygUsUGhpbGFkZWxwaGlhLCBQQSAoTWF5IDE0IHRoZSBiZXN0IGRheSB0YXlsb3I%3D' },
      { title: 'Should\'ve Said No', datePerformed: '2023-05-19', location: 'Foxborough, MA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=J3zt47Nyd68&pp=ygU0IEZveGJvcm91Z2gsIE1BIChNYXkgMTkpIC0gJ1Nob3VsZCd2ZSBTYWlkIE5vIHRheWxvcg%3D%3D' },
      { title: 'Better Man', datePerformed: '2023-05-19', location: 'Foxborough, MA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=0ZJ2NtnycU4&pp=ygUsIEZveGJvcm91Z2gsIE1BIChNYXkgMTkpIC0gYmV0dGVyIG1hbiB0YXlsb3c%3D' },
      { title: 'Question...?', datePerformed: '2023-05-20', location: 'Foxborough, MA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=T8DBaWPTb_0&pp=ygUnIEZveGJvcm91Z2gsIE1BIChNYXkgMjAgcXVlc3Rpb24gdGF5bG9y' },
      { title: 'Invisible', datePerformed: '2023-05-20', location: 'Foxborough, MA', featured: '-', videoLink: 'https://www.youtube.com/shorts/O1NcOveLs_U' },
      { title: 'I Think He Knows', datePerformed: '2023-05-21', location: 'Foxborough, MA', featured: '-', videoLink: 'https://www.youtube.com/watch?v=7K2voHQI91I&ab_channel=RusselBautista' },
      { title: 'Red', datePerformed: '2023-05-21', location: 'Foxborough, MA', featured: '-', videoLink: 'https://www.youtube.com/shorts/OPVQrxwEG0E' },
      { title: 'Getaway Car', datePerformed: '2023-05-26', location: 'East Rutherford, NJ', featured: 'Jack Antonoff', videoLink: 'https://www.youtube.com/watch?v=aVdDGlgTPGs&ab_channel=ReyMarkMondragon' },
      { title: 'Maroon', datePerformed: '2023-05-26', location: 'East Rutherford, NJ', featured: '-', videoLink: '' },
      { title: 'Holy Ground', datePerformed: '2023-05-27', location: 'East Rutherford, NJ', featured: '-', videoLink: '' },
      { title: 'False God', datePerformed: '2023-05-27', location: 'East Rutherford, NJ', featured: '-', videoLink: '' },
      { title: 'Welcome To New York', datePerformed: '2023-05-28', location: 'East Rutherford, NJ', featured: '-', videoLink: '' },
      { title: 'Clean', datePerformed: '2023-05-28', location: 'East Rutherford, NJ', featured: '-', videoLink: '' },
      { title: 'I Wish You Would', datePerformed: '2023-06-02', location: 'Chicago, IL', featured: '-', videoLink: '' },
      { title: 'the lakes', datePerformed: '2023-06-02', location: 'Chicago, IL', featured: '-', videoLink: '' },
      { title: 'You All Over Me', datePerformed: '2023-06-03', location: 'Chicago, IL', featured: 'Maren Morris', videoLink: '' },
      { title: 'I Don\'t Wanna Live Forever', datePerformed: '2023-06-03', location: 'Chicago, IL', featured: '-', videoLink: '' },
      { title: 'Hits Different', datePerformed: '2023-06-04', location: 'Chicago, IL', featured: '-', videoLink: '' },
      { title: 'The Moment I Knew', datePerformed: '2023-06-04', location: 'Chicago, IL', featured: '-', videoLink: '' },
      { title: 'Haunted', datePerformed: '2023-06-09', location: 'Detroit, MI', featured: '-', videoLink: '' },
      { title: 'I Almost Do', datePerformed: '2023-06-09', location: 'Detroit, MI', featured: '-', videoLink: '' },
      { title: 'All You Had To Do Was Stay', datePerformed: '2023-06-10', location: 'Detroit, MI', featured: '-', videoLink: '' },
      { title: 'Breathe', datePerformed: '2023-06-10', location: 'Detroit, MI', featured: '-', videoLink: '' },
      { title: 'Mr. Perfectly Fine', datePerformed: '2023-06-16', location: 'Pittsburgh, PA', featured: '-', videoLink: '' },
      { title: 'The Last Time', datePerformed: '2023-06-16', location: 'Pittsburgh, PA', featured: '-', videoLink: '' },
      { title: 'seven', datePerformed: '2023-06-17', location: 'Pittsburgh, PA', featured: 'Aaron Dessner', videoLink: '' },
      { title: 'The Story of Us', datePerformed: '2023-06-17', location: 'Pittsburgh, PA', featured: '-', videoLink: '' },
      { title: 'Paper Rings', datePerformed: '2023-06-23', location: 'Minneapolis, MN', featured: '-', videoLink: '' },
      { title: 'If This Was A Movie', datePerformed: '2023-06-23', location: 'Minneapolis, MN', featured: '-', videoLink: '' },
      { title: 'Dear John', datePerformed: '2023-06-24', location: 'Minneapolis, MN', featured: '-', videoLink: '' },
      { title: 'Daylight', datePerformed: '2023-06-24', location: 'Minneapolis, MN', featured: '-', videoLink: '' },
      { title: 'I\'m Only Me When I\'m With You', datePerformed: '2023-06-30', location: 'Cincinnati, OH', featured: '-', videoLink: '' },
      { title: 'evermore', datePerformed: '2023-06-30', location: 'Cincinnati, OH', featured: '-', videoLink: '' },
      { title: 'ivy', datePerformed: '2023-07-01', location: 'Cincinnati, OH', featured: 'Aaron Dessner', videoLink: '' },
      { title: 'I miss you, I’m sorry', datePerformed: '2023-07-01', location: 'Cincinnati, OH', featured: 'Gracie Abrams', videoLink: '' },
      { title: 'Call It What You Want', datePerformed: '2023-07-01', location: 'Cincinnati, OH', featured: '-', videoLink: '' },
      { title: 'Never Grow Up', datePerformed: '2023-07-07', location: 'Kansas City, MO', featured: '-', videoLink: '' },
      { title: 'When Emma Falls in Love', datePerformed: '2023-07-07', location: 'Kansas City, MO', featured: '-', videoLink: '' },
      { title: 'Last Kiss', datePerformed: '2023-07-08', location: 'Kansas City, MO', featured: '-', videoLink: '' },
      { title: 'dorothea', datePerformed: '2023-07-08', location: 'Kansas City, MO', featured: '-', videoLink: '' },
      { title: 'Picture To Burn', datePerformed: '2023-07-14', location: 'Denver, CO', featured: '-', videoLink: '' },
      { title: 'Timeless', datePerformed: '2023-07-14', location: 'Denver, CO', featured: '-', videoLink: '' },
      { title: 'Starlight', datePerformed: '2023-07-15', location: 'Denver, CO', featured: '-', videoLink: '' },
      { title: 'Back To December', datePerformed: '2023-07-15', location: 'Denver, CO', featured: '-', videoLink: '' },
      { title: 'This Is Why We Can\'t Have Nice Things', datePerformed: '2023-07-22', location: 'Seattle, WA', featured: '-', videoLink: '' },
      { title: 'Everything Has Changed', datePerformed: '2023-07-22', location: 'Seattle, WA', featured: '-', videoLink: '' },
      { title: 'Message In A Bottle', datePerformed: '2023-07-23', location: 'Seattle, WA', featured: '-', videoLink: '' },
      { title: 'Tied Together With A Smile', datePerformed: '2023-07-23', location: 'Seattle, WA', featured: '-', videoLink: '' },
      { title: 'right where you left me', datePerformed: '2023-07-28', location: 'Santa Clara, CA', featured: 'Aaron Dessner', videoLink: '' },
      { title: 'Castles Crumbling', datePerformed: '2023-07-28', location: 'Santa Clara, CA', featured: '-', videoLink: '' },
      { title: 'Stay Stay Stay', datePerformed: '2023-07-29', location: 'Santa Clara, CA', featured: '-', videoLink: '' },
      { title: 'All of the Girls You\'ve Loved Before', datePerformed: '2023-07-29', location: 'Santa Clara, CA', featured: '-', videoLink: '' },
      { title: 'I Can See You', datePerformed: '2023-08-03', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'Maroon', datePerformed: '2023-08-03', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'Our Song', datePerformed: '2023-08-04', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'You Are In Love', datePerformed: '2023-08-04', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'Death By A Thousand Cuts', datePerformed: '2023-08-05', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'You\'re On Your Own, Kid', datePerformed: '2023-08-05', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'Dress', datePerformed: '2023-08-07', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'exile', datePerformed: '2023-08-07', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'I Know Places', datePerformed: '2023-08-08', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'King of My Heart', datePerformed: '2023-08-08', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'New Romantics', datePerformed: '2023-08-09', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'New Year\'s Day', datePerformed: '2023-08-09', location: 'Los Angeles, CA', featured: '-', videoLink: '' },
      { title: 'I Forgot That You Existed', datePerformed: '2023-08-24', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
      { title: 'Sweet Nothing', datePerformed: '2023-08-24', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
      { title: 'Tell Me Why', datePerformed: '2023-08-25', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
      { title: 'Snow on the Beach', datePerformed: '2023-08-25', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
      { title: 'Cornelia Street', datePerformed: '2023-08-26', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
      { title: 'You\'re On Your Own, Kid', datePerformed: '2023-08-26', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
      { title: 'Afterglow', datePerformed: '2023-08-27', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
      { title: 'Maroon', datePerformed: '2023-08-27', location: 'Mexico City, Mexico', featured: '-', videoLink: '' },
      
      //add argentina and buenos aires songs
      
      // 2024
      { title: 'Dear Reader', datePerformed: '2024-02-07', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
      { title: 'Holy Ground', datePerformed: '2024-02-07', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
      { title: 'Eyes Open', datePerformed: '2024-02-08', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
      { title: 'Electric Touch', datePerformed: '2024-02-08', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
      { title: 'Superman', datePerformed: '2024-02-09', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
      { title: 'The Outside', datePerformed: '2024-02-09', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
      { title: 'Come In With The Rain', datePerformed: '2024-02-10', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
      { title: 'You\'re On Your Own, Kid', datePerformed: '2024-02-10', location: 'Tokyo, Japan', featured: '-', videoLink: '' },
      { title: 'Red', datePerformed: '2024-02-16', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
      { title: 'You\'re Losing Me', datePerformed: '2024-02-16', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
      { title: 'Getaway Car/August/The Other Side of the Door', datePerformed: '2024-02-17', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
      { title: 'this is me trying', datePerformed: '2024-02-17', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
      { title: 'Come Back...Be Here/Daylight', datePerformed: '2024-02-18', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
      { title: 'Teardrops On My Guitar', datePerformed: '2024-02-18', location: 'Melbourne, Australia', featured: '-', videoLink: '' },
      { title: 'How You Get The Girl', datePerformed: '2024-02-23', location: 'Sydney, Australia', featured: '-', videoLink: '' },
      { title: 'White Horse/Coney Island', datePerformed: '2024-02-23', location: 'Sydney, Australia', featured: 'Sabrina Carpenter', videoLink: '' },
      { title: 'Should\'ve Said No/You\'re Not Sorry', datePerformed: '2024-02-24', location: 'Sydney, Australia', featured: '-', videoLink: '' },
      { title: 'New Year\'s Day/Peace', datePerformed: '2024-02-24', location: 'Sydney, Australia', featured: '-', videoLink: '' },
      { title: 'Is It Over Now?/I Wish You Would', datePerformed: '2024-02-25', location: 'Sydney, Australia', featured: '-', videoLink: '' },
      { title: 'Haunted/Exile', datePerformed: '2024-02-25', location: 'Sydney, Australia', featured: '-', videoLink: '' },
      { title: 'Would\'ve Could\'ve Should\'ve/Ivy', datePerformed: '2024-02-26', location: 'Sydney, Australia', featured: '-', videoLink: '' },
      { title: 'Forever & Always/Maroon', datePerformed: '2024-02-26', location: 'Sydney, Australia', featured: '-', videoLink: '' },
      { title: 'Mine/Starlight', datePerformed: '2024-03-02', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'I Don\'t Wanna Live Forever/Dress', datePerformed: '2024-03-02', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'Long Story Short/The Story of Us', datePerformed: '2024-03-03', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'Clean/Evermore', datePerformed: '2024-03-03', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'Foolish One/Tell Me Why', datePerformed: '2024-03-04', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'This Love/Call It What You Want', datePerformed: '2024-03-04', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'Death By A Thousand Cuts/Babe', datePerformed: '2024-03-07', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'Fifteen/You\'re On Your Own, Kid', datePerformed: '2024-03-07', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'Sparks Fly/Gold Rush', datePerformed: '2024-03-08', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'False God/"Slut!"', datePerformed: '2024-03-08', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'Tim McGraw/Cowboy Like Me', datePerformed: '2024-03-09', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'Mirrorball/Epiphany', datePerformed: '2024-03-09', location: 'Singapore, SG', featured: '-', videoLink: '' },
      { title: 'Paris', datePerformed: '2024-05-09', location: 'Paris, France', featured: '-', videoLink: '' },
      { title: 'loml', datePerformed: '2024-05-09', location: 'Paris, France', featured: '-', videoLink: '' },
      { title: 'Is It Over Now?/Out Of The Woods', datePerformed: '2024-05-10', location: 'Paris, France', featured: '-', videoLink: '' },
      { title: 'My Boy Only Breaks His Favourite Toys', datePerformed: '2024-05-10', location: 'Paris, France', featured: '-', videoLink: '' },
      { title: 'Hey Stephen', datePerformed: '2024-05-11', location: 'Paris, France', featured: '-', videoLink: '' },
      { title: 'Maroon', datePerformed: '2024-05-11', location: 'Paris, France', featured: '-', videoLink: '' },
      { title: 'The Alchemy/Treacherous', datePerformed: '2024-05-12', location: 'Paris, France', featured: '-', videoLink: '' },
      { title: 'Begin Again/Paris', datePerformed: '2024-05-12', location: 'Paris, France', featured: '-', videoLink: '' },
      { title: 'I Think He Knows/Gorgeous', datePerformed: '2024-05-17', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
      { title: 'Peter', datePerformed: '2024-05-17', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
      { title: 'Guilty As Sin?', datePerformed: '2024-05-18', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
      { title: 'Say Don\'t Go/Welcome To New York/Clean', datePerformed: '2024-05-18', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
      { title: 'Message In A Bottle/How You Get The Girl/New Romantics', datePerformed: '2024-05-19', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
      { title: 'How Did It End?', datePerformed: '2024-05-19', location: 'Stockholm, Sweden', featured: '-', videoLink: '' },
      { title: 'Come Back...Be Here/The Way I Loved You/The Other Side of the Door', datePerformed: '2024-05-24', location: 'Lisbon, Portugal', featured: '-', videoLink: '' },
      { title: 'Fresh Out The Slammer/High Infidelity', datePerformed: '2024-05-24', location: 'Lisbon, Portugal', featured: '-', videoLink: '' },
      { title: 'The Tortured Poets Department/Now That We Don\'t Talk', datePerformed: '2024-05-25', location: 'Lisbon, Portugal', featured: '-', videoLink: '' },
      { title: 'You\'re On Your Own, Kid/Long Live', datePerformed: '2024-05-25', location: 'Lisbon, Portugal', featured: '-', videoLink: '' },
      { title: 'Sparks Fly/I Can Fix Him (No Really I Can)', datePerformed: '2024-05-29', location: 'Madrid, Spain', featured: '-', videoLink: '' },
      { title: 'I Look In People\'s Windows/Snow on the Beach', datePerformed: '2024-05-29', location: 'Madrid, Spain', featured: '-', videoLink: '' },
      { title: 'Our Song/Jump Then Fall', datePerformed: '2024-05-30', location: 'Madrid, Spain', featured: '-', videoLink: '' },
      { title: 'King of my Heart', datePerformed: '2024-05-30', location: 'Madrid, Spain', featured: '-', videoLink: '' },
      { title: 'The Prophecy/Long Story Short', datePerformed: '2024-06-02', location: 'Lyon, France', featured: '-', videoLink: '' },
      { title: 'Fifteen/You\'re On Your Own, Kid', datePerformed: '2024-06-02', location: 'Lyon, France', featured: '-', videoLink: '' },
      { title: 'Glitch/Everything Has Changed', datePerformed: '2024-06-03', location: 'Lyon, France', featured: '-', videoLink: '' },
      { title: 'Chloe, Sam, Sophia or Marcus', datePerformed: '2024-06-03', location: 'Lyon, France', featured: '-', videoLink: '' },
      { title: 'Would\'ve, Could\'ve, Should\'ve/I Know Places', datePerformed: '2024-06-07', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
      { title: '\'Tis The Damn Season/Daylight', datePerformed: '2024-06-07', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
      { title: 'The Bolter/Getaway Car', datePerformed: '2024-06-08', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
      { title: 'All Of The Girls You Loved Before/Crazier', datePerformed: '2024-06-08', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
      { title: 'It\'s Nice To Have A Friend/Dorothea', datePerformed: '2024-06-09', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
      { title: 'Haunted/Exile', datePerformed: '2024-06-09', location: 'Edinburgh, UK', featured: '-', videoLink: '' },
      { title: 'I Can See You/Mine', datePerformed: '2024-06-13', location: 'Liverpool, UK', featured: '-', videoLink: '' },
      { title: 'Cornelia Street/Maroon', datePerformed: '2024-06-13', location: 'Liverpool, UK', featured: '-', videoLink: '' },
      { title: 'This Is What You Came For/Gold Rush', datePerformed: '2024-06-14', location: 'Liverpool, UK', featured: '-', videoLink: '' },
      { title: 'The Great War/You\'re Losing Me', datePerformed: '2024-06-14', location: 'Liverpool, UK', featured: '-', videoLink: '' },
      { title: 'Carolina/No Body, No Crime', datePerformed: '2024-06-15', location: 'Liverpool, UK', featured: '-', videoLink: '' },
      { title: 'The Manuscript/Red', datePerformed: '2024-06-15', location: 'Liverpool, UK', featured: '-', videoLink: '' },
      { title: 'I Forgot That You Existed/This Is Why We Can\'t Have Nice Things', datePerformed: '2024-06-18', location: 'Cardiff, UK', featured: '-', videoLink: '' },
      { title: 'I Hate It Here/the lakes', datePerformed: '2024-06-18', location: 'Cardiff, UK', featured: '-', videoLink: '' },
      { title: 'Hits Different/Death By A Thousand Cuts', datePerformed: '2024-06-21', location: 'London, UK', featured: '-', videoLink: '' },
      { title: 'The Black Dog/Come Back...Be Here/Maroon', datePerformed: '2024-06-21', location: 'London, UK', featured: '-', videoLink: '' },
      { title: 'thanK you aIMee/Mean', datePerformed: '2024-06-22', location: 'London, UK', featured: '-', videoLink: '' },
      { title: 'Castles Crumbling', datePerformed: '2024-06-22', location: 'London, UK', featured: 'Hayley Williams', videoLink: '' },
      { title: 'us', datePerformed: '2024-06-23', location: 'London, UK', featured: 'Gracie Abrams', videoLink: '' },
      { title: 'Out of the Woods/Is It Over Now?/Clean', datePerformed: '2024-06-23', location: 'London, UK', featured: '-', videoLink: '' },
      { title: 'State of Grace/You\'re On Your Own, Kid', datePerformed: '2024-06-28', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
      { title: 'Sweet Nothing/Hoax', datePerformed: '2024-06-28', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
      { title: 'The Albatross/Dancing With Our Hands Tied', datePerformed: '2024-06-29', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
      { title: 'This Love/Ours', datePerformed: '2024-06-29', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
      { title: 'Clara Bow/The Lucky One', datePerformed: '2024-06-30', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
      { title: 'You\'re On Your Own, Kid', datePerformed: '2024-06-30', location: 'Dublin, Ireland', featured: '-', videoLink: '' },
      { title: 'Guilty As Sin?/Untouchable', datePerformed: '2024-07-04', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
      { title: 'The Archer/Question...?', datePerformed: '2024-07-04', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
      { title: 'imgonnagetyouback/Dress', datePerformed: '2024-07-05', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
      { title: 'You Are In Love/Cowboy Like Me', datePerformed: '2024-07-05', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
      { title: 'Sweeter Than Fiction/Holy Ground', datePerformed: '2024-07-06', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
      { title: 'Mary\'s Song (Oh My My My)/So High School/Everything Has Changed', datePerformed: '2024-07-06', location: 'Amsterdam, Netherlands', featured: '-', videoLink: '' },
      { title: 'Right Where You Left Me/All You Had To Do Was Stay', datePerformed: '2024-07-09', location: 'Zürich, Switzerland', featured: '-', videoLink: '' },
      { title: 'Last Kiss/Sad Beautiful Tragic', datePerformed: '2024-07-09', location: 'Zürich, Switzerland', featured: '-', videoLink: '' },
      { title: 'Closure/A Perfectly Good Heart', datePerformed: '2024-07-10', location: 'Zürich, Switzerland', featured: '-', videoLink: '' },
      { title: 'Robin/Never Grow Up', datePerformed: '2024-07-10', location: 'Zürich, Switzerland', featured: '-', videoLink: '' },
      { title: 'The 1/Wonderland', datePerformed: '2024-07-13', location: 'Milan, Italy', featured: '-', videoLink: '' },
      { title: 'I Almost Do/The Moment I Knew', datePerformed: '2024-07-13', location: 'Milan, Italy', featured: '-', videoLink: '' },
      { title: 'Mr. Perfectly Fine/Red', datePerformed: '2024-07-14', location: 'Milan, Italy', featured: '-', videoLink: '' },
      { title: 'Getaway Car/Out of the Woods', datePerformed: '2024-07-14', location: 'Milan, Italy', featured: '-', videoLink: '' },
      { title: 'Superstar/Invisible String', datePerformed: '2024-07-17', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
      { title: '"Slut!"/False God', datePerformed: '2024-07-17', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
      { title: 'Speak Now/Hey Stephen', datePerformed: '2024-07-18', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
      { title: 'This Is Me Trying/Labyrinth', datePerformed: '2024-07-18', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
      { title: 'Paper Rings/Stay Stay Stay', datePerformed: '2024-07-19', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
      { title: 'it\'s time to go/Better Man', datePerformed: '2024-07-19', location: 'Gelsenkirchen, Germany', featured: '-', videoLink: '' },
      { title: 'Teardrops On My Guitar/The Last Time', datePerformed: '2024-07-23', location: 'Hamburg, Germany', featured: '-', videoLink: '' },
      { title: 'We Were Happy/Happiness', datePerformed: '2024-07-23', location: 'Hamburg, Germany', featured: '-', videoLink: '' },
      { title: 'The Last Great American Dynasty/Run', datePerformed: '2024-07-24', location: 'Hamburg, Germany', featured: '-', videoLink: 'https://www.youtube.com/watch?v=K27p-0TZ5s8&ab_channel=katis90' },
      { title: 'Nothing New/Dear Reader', datePerformed: '2024-07-24', location: 'Hamburg, Germany', featured: '-', videoLink: '' },  
      
  ]

  export default SongsArray